[package]
name = "xops"
version = "0.1.0"
edition = "2018"
license = "MIT OR Apache-2.0"

[workspace]
members = [
    "xops_macros",
    "xops_core",
]

[dependencies]
xops_macros = { path = "xops_macros" }