[package]
name = "xops_core"
version = "0.1.0"
edition = "2018"

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
darling = "0.13.0"

[dependencies.syn]
version = "1.0"
features = ["extra-traits", "full"]